use anyhow::{anyhow, Result};
use tokio::fs;
use tracing::info;
use super::McpManager;

pub struct McpEvolver {
    manager: McpManager,
    dynamic_dir: String,
}

impl McpEvolver {
    pub fn new(manager: McpManager, runtime_path: &str) -> Self {
        let dynamic_dir = format!("{}/mcp-servers/dynamic", runtime_path);
        Self {
            manager,
            dynamic_dir,
        }
    }

    pub async fn init(&self) -> Result<()> {
        fs::create_dir_all(&self.dynamic_dir).await?;
        Ok(())
    }

    /// Create a new MCP server from code generated by an LLM
    pub async fn create_server(
        &self,
        name: &str,
        lang: &str,
        code: &str,
        emit_event: bool,
    ) -> Result<String> {
        let server_dir = format!("{}/{}", self.dynamic_dir, name);
        fs::create_dir_all(&server_dir).await?;

        let (command, args) = match lang.to_lowercase().as_str() {
            "node" | "javascript" | "js" => {
                let file_path = format!("{}/index.js", server_dir);
                fs::write(&file_path, code).await?;

                // Initialize package.json if it doesn't exist
                let pkg_json = format!(
                    r#"{{
  "name": "{}",
  "version": "1.0.0",
  "dependencies": {{
    "@modelcontextprotocol/sdk": "latest"
  }}
}}"#,
                    name
                );
                fs::write(format!("{}/package.json", server_dir), pkg_json).await?;

                // Install dependencies
                info!("Installing dependencies for dynamic MCP server: {}", name);
                let output = tokio::process::Command::new("npm")
                    .arg("install")
                    .current_dir(&server_dir)
                    .output()
                    .await?;

                if !output.status.success() {
                    let err = String::from_utf8_lossy(&output.stderr);
                    return Err(anyhow!("Failed to install npm dependencies: {}", err));
                }

                ("node".to_string(), vec![file_path])
            }
            "python" | "py" => {
                let file_path = format!("{}/server.py", server_dir);
                fs::write(&file_path, code).await?;
                ("python3".to_string(), vec![file_path])
            }
            _ => return Err(anyhow!("Unsupported language: {}", lang)),
        };

        // Register with the manager
        self.manager.add_dynamic_server(name, &command, args).await?;

        // Broadcast to mesh if requested
        if emit_event {
            let event = crate::events::SystemEvent::CapabilityCreated {
                name: name.to_string(),
                language: lang.to_string(),
                source_code: code.to_string(),
            };
            let _ = self.manager.event_bus.send(event);
        }

        Ok(format!(
            "Successfully created and started MCP server '{}'",
            name
        ))
    }
}
